#!/usr/bin/env node

'use strict'

var c = require('skilstak-colors');

console.log(c.b + "Welcome to the dice game");

function randInt(min,max) {
  return Math.floor((Math.random() * (max - min + 1))+min);
}

var total = 0;
for (var n=0; n < 5; n++) {
  var side = randInt(1,6)
  console.log(c.m + "You rolled a " + side);
  total+= side;
}

console.log(c.b + "TOTAL: " + total);

if (total <= 15) {
  console.log(c.y + "... yikes... not good...");
}

